name: crypto_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: 4.7.3
  firebase_auth_platform_interface: 6.18.0
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6
  dio: ^5.0.2
  get_it: ^7.2.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  intl: ^0.18.0
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/Coin_Logo/
